// <auto-generated />
namespace FR_BaseDonnee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FirstTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202105171513060_First Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
